[window]

startup_mode = "Maximized"
dynamic_title = false
decorations = "None"
opacity = 0.69

padding = { x = 69 , y = 42 }

[colors]

primary.foreground = "#e4e4e7"
primary.background = "#09090b"

[font]

size = 20

[terminal]

shell  = "cmd"